name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/smartscreenshot

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy smartscreenshot \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/smartscreenshot \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
